apiVersion: v1
kind: Service
metadata:
  name: {{ include "barkuni-app.fullname" . }}
  labels:
    {{- include "barkuni-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "barkuni-app.selectorLabels" . | nindent 4 }}
