---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "barkuni-app.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "barkuni-app.fullname" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "barkuni-app.fullname" . }}
    namespace: app
roleRef:
  kind: ClusterRole
  name: {{ include "barkuni-app.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
